# {{ title }}

TYPO3 project created with [foundry](https://github.com/bmack/foundry).

| | |
| --- | --- |
| TYPO3 | {{ typo3Label }} (`{{ typo3Constraint }}`) |
| Site package | `{{ composerName }}` in `packages/{{ project }}/` |
| Base | {{ baseLabel }} |

## Working locally

```bash
ddev start                  # https://{{ project }}.ddev.site/
ddev composer install
ddev typo3 extension:setup  # after adding or changing a package
```

- **Backend:** https://{{ project }}.ddev.site/typo3/ (`admin` / `Password.1`, development only)
- **Site configuration:** `config/sites/` (committed)
- **Local settings:** `config/system/settings.php` is generated by `typo3 setup` and not committed; `config/system/additional.php` adds the DDEV settings.

## Site package

Everything project specific lives in `packages/{{ project }}/`: the Site Set in
`Configuration/Sets/Main/` and, depending on the base, the page templates in
`Resources/Private/Pages/`, `Layouts/` and `Partials/`, content element templates in
`Resources/Private/Content/`. Site configuration references the set as its dependency.

Commit `composer.lock` and `config/sites/`: a project, unlike a throwaway instance, needs both.
